export const cities = [
  { country: "Cuba", geonameid: 3533753, name: "Yara", subcountry: "Granma" },
  {
    country: "Cuba",
    geonameid: 3533826,
    name: "Yaguajay",
    subcountry: "Sancti Sp\u00edritus",
  },
  {
    country: "Cuba",
    geonameid: 3534094,
    name: "Vi\u00f1ales",
    subcountry: "Pinar del R\u00edo",
  },
  {
    country: "Cuba",
    geonameid: 3534363,
    name: "Vertientes",
    subcountry: "Camag\u00fcey",
  },
  {
    country: "Cuba",
    geonameid: 3534432,
    name: "Venezuela",
    subcountry: "Ciego de \u00c1vila",
  },
  {
    country: "Cuba",
    geonameid: 3534632,
    name: "Varadero",
    subcountry: "Matanzas",
  },
  {
    country: "Cuba",
    geonameid: 3534749,
    name: "San Germ\u00e1n",
    subcountry: "Holgu\u00edn",
  },
  {
    country: "Cuba",
    geonameid: 3534761,
    name: "Uni\u00f3n de Reyes",
    subcountry: "Matanzas",
  },
  {
    country: "Cuba",
    geonameid: 3534915,
    name: "Trinidad",
    subcountry: "Sancti Sp\u00edritus",
  },
  {
    country: "Cuba",
    geonameid: 3536259,
    name: "Sibanic\u00fa",
    subcountry: "Camag\u00fcey",
  },
  {
    country: "Cuba",
    geonameid: 3536640,
    name: "Santo Domingo",
    subcountry: "Villa Clara",
  },
  {
    country: "Cuba",
    geonameid: 3536724,
    name: "Santiago de las Vegas",
    subcountry: "La Habana",
  },
  {
    country: "Cuba",
    geonameid: 3536729,
    name: "Santiago de Cuba",
    subcountry: "Santiago de Cuba",
  },
  {
    country: "Cuba",
    geonameid: 3537840,
    name: "Santa Cruz del Sur",
    subcountry: "Camag\u00fcey",
  },
  {
    country: "Cuba",
    geonameid: 3537845,
    name: "Santa Cruz del Norte",
    subcountry: "Mayabeque",
  },
  {
    country: "Cuba",
    geonameid: 3537906,
    name: "Santa Clara",
    subcountry: "Villa Clara",
  },
  {
    country: "Cuba",
    geonameid: 3538803,
    name: "San Miguel del Padr\u00f3n",
    subcountry: "La Habana",
  },
  {
    country: "Cuba",
    geonameid: 3539093,
    name: "San Luis",
    subcountry: "Santiago de Cuba",
  },
  {
    country: "Cuba",
    geonameid: 3539560,
    name: "San Jos\u00e9 de las Lajas",
    subcountry: "Mayabeque",
  },
  {
    country: "Cuba",
    geonameid: 3540667,
    name: "Sancti Sp\u00edritus",
    subcountry: "Sancti Sp\u00edritus",
  },
  {
    country: "Cuba",
    geonameid: 3540680,
    name: "San Cristobal",
    subcountry: "Artemisa",
  },
  {
    country: "Cuba",
    geonameid: 3540885,
    name: "San Antonio de los Ba\u00f1os",
    subcountry: "Artemisa",
  },
  {
    country: "Cuba",
    geonameid: 3541440,
    name: "Sagua la Grande",
    subcountry: "Villa Clara",
  },
  {
    country: "Cuba",
    geonameid: 3541446,
    name: "Sagua de T\u00e1namo",
    subcountry: "Holgu\u00edn",
  },
  {
    country: "Cuba",
    geonameid: 3541999,
    name: "Rodas",
    subcountry: "Cienfuegos",
  },
  {
    country: "Cuba",
    geonameid: 3542137,
    name: "R\u00edo Guayabal de Yateras",
    subcountry: "Guant\u00e1namo",
  },
  {
    country: "Cuba",
    geonameid: 3542167,
    name: "R\u00edo Cauto",
    subcountry: "Granma",
  },
  {
    country: "Cuba",
    geonameid: 3542455,
    name: "Remedios",
    subcountry: "Villa Clara",
  },
  {
    country: "Cuba",
    geonameid: 3542502,
    name: "Regla",
    subcountry: "La Habana",
  },
  {
    country: "Cuba",
    geonameid: 3542744,
    name: "Ranchuelo",
    subcountry: "Villa Clara",
  },
  {
    country: "Cuba",
    geonameid: 3543299,
    name: "Puerto Padre",
    subcountry: "Las Tunas",
  },
  {
    country: "Cuba",
    geonameid: 3543498,
    name: "Primero de Enero",
    subcountry: "Ciego de \u00c1vila",
  },
  {
    country: "Cuba",
    geonameid: 3543961,
    name: "Placetas",
    subcountry: "Villa Clara",
  },
  {
    country: "Cuba",
    geonameid: 3544091,
    name: "Pinar del R\u00edo",
    subcountry: "Pinar del R\u00edo",
  },
  {
    country: "Cuba",
    geonameid: 3544393,
    name: "Perico",
    subcountry: "Matanzas",
  },
  {
    country: "Cuba",
    geonameid: 3544607,
    name: "Pedro Betancourt",
    subcountry: "Matanzas",
  },
  {
    country: "Cuba",
    geonameid: 3545040,
    name: "Palmira",
    subcountry: "Cienfuegos",
  },
  {
    country: "Cuba",
    geonameid: 3545064,
    name: "Palma Soriano",
    subcountry: "Santiago de Cuba",
  },
  {
    country: "Cuba",
    geonameid: 3545841,
    name: "Nuevitas",
    subcountry: "Camag\u00fcey",
  },
  {
    country: "Cuba",
    geonameid: 3545867,
    name: "Nueva Gerona",
    subcountry: "Isla de la Juventud",
  },
  {
    country: "Cuba",
    geonameid: 3545981,
    name: "Niquero",
    subcountry: "Granma",
  },
  {
    country: "Cuba",
    geonameid: 3546434,
    name: "Mor\u00f3n",
    subcountry: "Ciego de \u00c1vila",
  },
  {
    country: "Cuba",
    geonameid: 3546791,
    name: "Moa",
    subcountry: "Holgu\u00edn",
  },
  {
    country: "Cuba",
    geonameid: 3546882,
    name: "Minas de Matahambre",
    subcountry: "Pinar del R\u00edo",
  },
  {
    country: "Cuba",
    geonameid: 3546894,
    name: "Minas",
    subcountry: "Camag\u00fcey",
  },
  {
    country: "Cuba",
    geonameid: 3547260,
    name: "Media Luna",
    subcountry: "Granma",
  },
  {
    country: "Cuba",
    geonameid: 3547398,
    name: "Matanzas",
    subcountry: "Matanzas",
  },
  {
    country: "Cuba",
    geonameid: 3547600,
    name: "Mariel",
    subcountry: "Artemisa",
  },
  {
    country: "Cuba",
    geonameid: 3547867,
    name: "Manzanillo",
    subcountry: "Granma",
  },
  {
    country: "Cuba",
    geonameid: 3547976,
    name: "Manicaragua",
    subcountry: "Villa Clara",
  },
  {
    country: "Cuba",
    geonameid: 3548441,
    name: "Mais\u00ed",
    subcountry: "Guant\u00e1namo",
  },
  {
    country: "Cuba",
    geonameid: 3548529,
    name: "Madruga",
    subcountry: "Mayabeque",
  },
  {
    country: "Cuba",
    geonameid: 3548993,
    name: "Los Palacios",
    subcountry: "Pinar del R\u00edo",
  },
  {
    country: "Cuba",
    geonameid: 3550598,
    name: "Las Tunas",
    subcountry: "Las Tunas",
  },
  {
    country: "Cuba",
    geonameid: 3551184,
    name: "La Sierpe",
    subcountry: "Sancti Sp\u00edritus",
  },
  {
    country: "Cuba",
    geonameid: 3551608,
    name: "La Salud",
    subcountry: "Mayabeque",
  },
  {
    country: "Cuba",
    geonameid: 3553478,
    name: "Havana",
    subcountry: "La Habana",
  },
  {
    country: "Cuba",
    geonameid: 3555907,
    name: "Jovellanos",
    subcountry: "Matanzas",
  },
  {
    country: "Cuba",
    geonameid: 3556077,
    name: "Jobabo",
    subcountry: "Holgu\u00edn",
  },
  {
    country: "Cuba",
    geonameid: 3556078,
    name: "Jobabo",
    subcountry: "Las Tunas",
  },
  {
    country: "Cuba",
    geonameid: 3556168,
    name: "Jiguan\u00ed",
    subcountry: "Granma",
  },
  {
    country: "Cuba",
    geonameid: 3556268,
    name: "Jes\u00fas Men\u00e9ndez",
    subcountry: "Las Tunas",
  },
  {
    country: "Cuba",
    geonameid: 3556334,
    name: "Jatibonico",
    subcountry: "Sancti Sp\u00edritus",
  },
  {
    country: "Cuba",
    geonameid: 3556351,
    name: "Jaruco",
    subcountry: "Mayabeque",
  },
  {
    country: "Cuba",
    geonameid: 3556437,
    name: "Jag\u00fcey Grande",
    subcountry: "Matanzas",
  },
  {
    country: "Cuba",
    geonameid: 3556969,
    name: "Holgu\u00edn",
    subcountry: "Holgu\u00edn",
  },
  { country: "Cuba", geonameid: 3557332, name: "Guisa", subcountry: "Granma" },
  {
    country: "Cuba",
    geonameid: 3557347,
    name: "G\u00fcira de Melena",
    subcountry: "Artemisa",
  },
  {
    country: "Cuba",
    geonameid: 3557378,
    name: "G\u00fcines",
    subcountry: "Mayabeque",
  },
  {
    country: "Cuba",
    geonameid: 3557689,
    name: "Guant\u00e1namo",
    subcountry: "Guant\u00e1namo",
  },
  {
    country: "Cuba",
    geonameid: 3557758,
    name: "Guane",
    subcountry: "Pinar del R\u00edo",
  },
  {
    country: "Cuba",
    geonameid: 3557801,
    name: "Guanajay",
    subcountry: "Artemisa",
  },
  {
    country: "Cuba",
    geonameid: 3557846,
    name: "Guanabacoa",
    subcountry: "La Habana",
  },
  {
    country: "Cuba",
    geonameid: 3557923,
    name: "Gu\u00e1imaro",
    subcountry: "Camag\u00fcey",
  },
  {
    country: "Cuba",
    geonameid: 3558315,
    name: "Gibara",
    subcountry: "Holgu\u00edn",
  },
  {
    country: "Cuba",
    geonameid: 3558744,
    name: "Fomento",
    subcountry: "Sancti Sp\u00edritus",
  },
  {
    country: "Cuba",
    geonameid: 3558771,
    name: "Florida",
    subcountry: "Camag\u00fcey",
  },
  {
    country: "Cuba",
    geonameid: 3558792,
    name: "Florencia",
    subcountry: "Ciego de \u00c1vila",
  },
  {
    country: "Cuba",
    geonameid: 3559318,
    name: "Esmeralda",
    subcountry: "Camag\u00fcey",
  },
  {
    country: "Cuba",
    geonameid: 3559416,
    name: "Encrucijada",
    subcountry: "Villa Clara",
  },
  {
    country: "Cuba",
    geonameid: 3562827,
    name: "Cumanayagua",
    subcountry: "Cienfuegos",
  },
  {
    country: "Cuba",
    geonameid: 3562895,
    name: "Cueto",
    subcountry: "Holgu\u00edn",
  },
  {
    country: "Cuba",
    geonameid: 3563145,
    name: "Cruces",
    subcountry: "Cienfuegos",
  },
  {
    country: "Cuba",
    geonameid: 3563317,
    name: "Corralillo",
    subcountry: "Villa Clara",
  },
  {
    country: "Cuba",
    geonameid: 3563504,
    name: "Contramaestre",
    subcountry: "Santiago de Cuba",
  },
  {
    country: "Cuba",
    geonameid: 3563559,
    name: "Consolaci\u00f3n del Sur",
    subcountry: "Pinar del R\u00edo",
  },
  {
    country: "Cuba",
    geonameid: 3563609,
    name: "Condado",
    subcountry: "Sancti Sp\u00edritus",
  },
  {
    country: "Cuba",
    geonameid: 3563843,
    name: "Col\u00f3n",
    subcountry: "Matanzas",
  },
  {
    country: "Cuba",
    geonameid: 3563856,
    name: "Colombia",
    subcountry: "Las Tunas",
  },
  {
    country: "Cuba",
    geonameid: 3564084,
    name: "Ciro Redondo",
    subcountry: "Ciego de \u00c1vila",
  },
  {
    country: "Cuba",
    geonameid: 3564114,
    name: "Cifuentes",
    subcountry: "Villa Clara",
  },
  {
    country: "Cuba",
    geonameid: 3564124,
    name: "Cienfuegos",
    subcountry: "Cienfuegos",
  },
  {
    country: "Cuba",
    geonameid: 3564178,
    name: "Ciego de \u00c1vila",
    subcountry: "Ciego de \u00c1vila",
  },
  {
    country: "Cuba",
    geonameid: 3564394,
    name: "Chambas",
    subcountry: "Ciego de \u00c1vila",
  },
  {
    country: "Cuba",
    geonameid: 3564436,
    name: "Cerro",
    subcountry: "La Habana",
  },
  {
    country: "Cuba",
    geonameid: 3564885,
    name: "Cauto Cristo",
    subcountry: "Granma",
  },
  {
    country: "Cuba",
    geonameid: 3565432,
    name: "C\u00e1rdenas",
    subcountry: "Matanzas",
  },
  {
    country: "Cuba",
    geonameid: 3565951,
    name: "Campechuela",
    subcountry: "Granma",
  },
  {
    country: "Cuba",
    geonameid: 3566054,
    name: "Camajuan\u00ed",
    subcountry: "Villa Clara",
  },
  {
    country: "Cuba",
    geonameid: 3566067,
    name: "Camag\u00fcey",
    subcountry: "Camag\u00fcey",
  },
  {
    country: "Cuba",
    geonameid: 3566134,
    name: "Calimete",
    subcountry: "Matanzas",
  },
  {
    country: "Cuba",
    geonameid: 3566356,
    name: "Caibari\u00e9n",
    subcountry: "Villa Clara",
  },
  {
    country: "Cuba",
    geonameid: 3566429,
    name: "Cacocum",
    subcountry: "Holgu\u00edn",
  },
  {
    country: "Cuba",
    geonameid: 3566603,
    name: "Cabaigu\u00e1n",
    subcountry: "Sancti Sp\u00edritus",
  },
  {
    country: "Cuba",
    geonameid: 3567546,
    name: "Bejucal",
    subcountry: "Mayabeque",
  },
  { country: "Cuba", geonameid: 3567597, name: "Bayamo", subcountry: "Granma" },
  {
    country: "Cuba",
    geonameid: 3567612,
    name: "Bauta",
    subcountry: "Artemisa",
  },
  {
    country: "Cuba",
    geonameid: 3567669,
    name: "Bartolom\u00e9 Mas\u00f3",
    subcountry: "Granma",
  },
  {
    country: "Cuba",
    geonameid: 3567823,
    name: "Baragu\u00e1",
    subcountry: "Ciego de \u00c1vila",
  },
  {
    country: "Cuba",
    geonameid: 3567834,
    name: "Baracoa",
    subcountry: "Guant\u00e1namo",
  },
  {
    country: "Cuba",
    geonameid: 3567869,
    name: "Banes",
    subcountry: "Holgu\u00edn",
  },
  {
    country: "Cuba",
    geonameid: 3567995,
    name: "Bah\u00eda Honda",
    subcountry: "Artemisa",
  },
  {
    country: "Cuba",
    geonameid: 3568312,
    name: "Artemisa",
    subcountry: "Artemisa",
  },
  {
    country: "Cuba",
    geonameid: 3568342,
    name: "Arroyo Naranjo",
    subcountry: "La Habana",
  },
  {
    country: "Cuba",
    geonameid: 3569024,
    name: "Amancio",
    subcountry: "Las Tunas",
  },
  {
    country: "Cuba",
    geonameid: 3569136,
    name: "Alqu\u00edzar",
    subcountry: "Artemisa",
  },
  {
    country: "Cuba",
    geonameid: 3569370,
    name: "Alamar",
    subcountry: "La Habana",
  },
  {
    country: "Cuba",
    geonameid: 3569546,
    name: "Aguada de Pasajeros",
    subcountry: "Cienfuegos",
  },
  {
    country: "Cuba",
    geonameid: 3569741,
    name: "Abreus",
    subcountry: "Cienfuegos",
  },
  {
    country: "Cuba",
    geonameid: 3746181,
    name: "Habana del Este",
    subcountry: "La Habana",
  },
  {
    country: "Cuba",
    geonameid: 3746183,
    name: "Centro Habana",
    subcountry: "La Habana",
  },
  {
    country: "Cuba",
    geonameid: 3746184,
    name: "La Habana Vieja",
    subcountry: "La Habana",
  },
  {
    country: "Cuba",
    geonameid: 3746938,
    name: "B\u00e1guanos",
    subcountry: "Holgu\u00edn",
  },
  {
    country: "Cuba",
    geonameid: 3754915,
    name: "Jimaguay\u00fa",
    subcountry: "Camag\u00fcey",
  },
  {
    country: "Cuba",
    geonameid: 6956646,
    name: "Arroyo Naranjo",
    subcountry: "La Habana",
  },
  {
    country: "Cuba",
    geonameid: 6956647,
    name: "Boyeros",
    subcountry: "La Habana",
  },
  {
    country: "Cuba",
    geonameid: 6956648,
    name: "Diez de Octubre",
    subcountry: "La Habana",
  },
];
