export enum ProductCategory {
  ALIMENTOS = "Alimentos",
  ARTESANIA_MANUALIDADES = "Artesanía y Manualidades",
  BEBIDAS = "Bebidas",
  BELLEZA_SALUD = "Belleza y Salud",
  CAMARAS_FOTOGRAFIA = "Cámaras y Fotografía",
  COMPUTADORAS_TABLETAS = "Computadoras y Tabletas",
  DEPORTE = "Deporte",
  ELECTRODOMESTICOS = "Electrodomésticos",
  HOGAR = "Hogar",
  JARDINERIA_BRICOLAJE = "Jarinería y Bricolaje",
  JUEGOS_JUGUETES = "Juegos y Juguetes",
  LIBROS_REVISTAS_COMICS = "Libros, Revistas y Cómics",
  MASCOTAS = "Mascotas",
  PRODUCTOS_BEBES = "Productos para Bebés",
  RELOJES_JOYAS = "Relojes y Joyas",
  ROPA_CALZADO = "Ropa y Calzado",
  TELOFIONIA = "Telefonía",
  VEHICULOS_ACCESORIOS = "Vehículos y Accesorios",
}
